import type {
  Transfer,
  WebhookEndpoint,
  PaymentIntent,
  CheckoutSession,
  PaymentLink,
  Refund,
  TransferAccount,
  SubscriptionIntent,
  Subscription,
  Charge,
  BankingLink,
  Movement,
  RefreshIntent,
  TeamMember,
  ApiKeyInfo,
  Report,
  Institution,
} from "./types";

// ── Transfers ──

export const mockTransfers: Transfer[] = [
  {
    id: "txn_001",
    counterparty: {
      holderName: "Juan Pérez",
      holderId: "12.345.678-9",
      institutionName: "Banco de Chile",
      institutionId: "bch",
      accountType: "checking_account",
      accountNumber: "00-123-45678-90",
      email: "juan.perez@email.com",
    },
    status: "succeeded",
    type: "outbound",
    amountCents: 15000000,
    currency: "CLP",
    metadata: { concept: "Pago nómina febrero" },
    transactionDate: "2026-02-27",
    returnReason: null,
    comment: "Pago nómina febrero",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-27T10:30:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: { id: "batch_001", description: "Nómina Febrero 2026" },
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_002",
    counterparty: {
      holderName: "María González",
      holderId: "98.765.432-1",
      institutionName: "BancoEstado",
      institutionId: "bse",
      accountType: "sight_account",
      accountNumber: "00-456-78901-23",
      email: null,
    },
    status: "succeeded",
    type: "inbound",
    amountCents: 8950000,
    currency: "CLP",
    metadata: { orderId: "4521" },
    transactionDate: "2026-02-26",
    returnReason: null,
    comment: "Compra online #4521",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-26T14:15:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_003",
    counterparty: {
      holderName: "Proveedor Tecnología SA",
      holderId: "76.543.210-K",
      institutionName: "Banco Santander",
      institutionId: "bsa",
      accountType: "checking_account",
      accountNumber: "00-789-01234-56",
      email: "pagos@provtec.cl",
    },
    status: "pending",
    type: "outbound",
    amountCents: 250000000,
    currency: "CLP",
    metadata: { invoiceId: "INV-2026-0042" },
    transactionDate: null,
    returnReason: null,
    comment: "Pago factura servicios cloud",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-27T09:00:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_004",
    counterparty: {
      holderName: "Carlos Muñoz",
      holderId: "11.222.333-4",
      institutionName: "Banco BCI",
      institutionId: "bbi",
      accountType: "savings_account",
      accountNumber: "00-111-22233-44",
      email: null,
    },
    status: "failed",
    type: "inbound",
    amountCents: 4500000,
    currency: "CLP",
    metadata: {},
    transactionDate: null,
    returnReason: null,
    comment: "Transferencia rechazada - fondos insuficientes",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-25T16:45:00Z",
    reversedAt: null,
    failedAt: "2026-02-25T16:46:00Z",
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_005",
    counterparty: {
      holderName: "Startup Chile SPA",
      holderId: "77.888.999-0",
      institutionName: "Banco Itaú",
      institutionId: "bit",
      accountType: "checking_account",
      accountNumber: "00-555-66677-88",
      email: "finance@startupchile.cl",
    },
    status: "succeeded",
    type: "inbound",
    amountCents: 32000000,
    currency: "CLP",
    metadata: { project: "Q1-reembolso" },
    transactionDate: "2026-02-24",
    returnReason: null,
    comment: "Reembolso proyecto Q1",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-24T11:00:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_006",
    counterparty: {
      holderName: "Juan Pérez",
      holderId: "12.345.678-9",
      institutionName: "Banco de Chile",
      institutionId: "bch",
      accountType: "checking_account",
      accountNumber: "00-123-45678-90",
      email: "juan.perez@email.com",
    },
    status: "returned",
    type: "outbound",
    amountCents: 120000000,
    currency: "CLP",
    metadata: { reason: "Pago duplicado" },
    transactionDate: "2026-02-23",
    returnReason: "Pago duplicado detectado",
    comment: "Pago duplicado - reversado",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-23T08:30:00Z",
    reversedAt: "2026-02-23T10:15:00Z",
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_007",
    counterparty: {
      holderName: "Ana López",
      holderId: "15.678.901-2",
      institutionName: "Banco Falabella",
      institutionId: "bfa",
      accountType: "sight_account",
      accountNumber: "00-999-88877-66",
      email: null,
    },
    status: "succeeded",
    type: "inbound",
    amountCents: 7500000,
    currency: "CLP",
    metadata: {},
    transactionDate: "2026-02-27",
    returnReason: null,
    comment: "Pago arriendo estacionamiento",
    accountNumber: {
      number: "00-987-65432-10",
      accountId: "acc_001",
      accountDescription: "Cuenta corriente empresa",
    },
    trackingKey: null,
    createdAt: "2026-02-27T07:00:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: null,
    receiptUrl: null,
  },
  {
    id: "txn_008",
    counterparty: {
      holderName: "Empresa Mexicana SA de CV",
      holderId: null,
      institutionName: "BBVA México",
      institutionId: "bbva_mx",
      accountType: "clabe",
      accountNumber: "012345678901234567",
      email: "pagos@empresa-mx.com",
    },
    status: "pending",
    type: "outbound",
    amountCents: 5000000,
    currency: "MXN",
    metadata: { concept: "Inversión seed round" },
    transactionDate: null,
    returnReason: null,
    comment: "Inversión seed round",
    accountNumber: {
      number: "012345678901234567",
      accountId: "acc_002",
      accountDescription: "Cuenta CLABE empresa",
    },
    trackingKey: "TRK-2026-0227-001",
    createdAt: "2026-02-27T12:00:00Z",
    reversedAt: null,
    failedAt: null,
    rejectedAt: null,
    transferBatch: null,
    referenceId: "REF-SEED-001",
    receiptUrl: null,
  },
];

// ── Webhooks ──

export const mockWebhooks: WebhookEndpoint[] = [
  {
    id: "wh_001",
    url: "https://mi-app.com/webhooks/fintoc",
    status: "enabled",
    events: ["transfer.created", "transfer.succeeded", "transfer.failed"],
    createdAt: "2026-01-15T10:00:00Z",
    description: "Webhook principal de transferencias",
  },
  {
    id: "wh_002",
    url: "https://mi-app.com/webhooks/payments",
    status: "enabled",
    events: ["payment_intent.succeeded", "payment_intent.failed"],
    createdAt: "2026-02-01T14:30:00Z",
    description: "Webhook de pagos",
  },
  {
    id: "wh_003",
    url: "https://staging.mi-app.com/webhooks",
    status: "disabled",
    events: ["transfer.created"],
    createdAt: "2025-12-20T09:00:00Z",
    description: "Webhook staging (deshabilitado)",
  },
];

// ── Payment Intents ──

export const mockPaymentIntents: PaymentIntent[] = [
  {
    id: "pi_001",
    amount: 25000,
    currency: "CLP",
    status: "succeeded",
    recipientAccount: {
      holderId: "76.123.456-7",
      holderName: "Mi Empresa SpA",
      institutionId: "bch",
      number: "00-987-65432-10",
      type: "checking_account",
    },
    senderAccount: {
      holderId: "12.345.678-9",
      holderName: "Juan Pérez",
      institutionId: "bse",
      number: "00-456-78901-23",
      type: "sight_account",
    },
    widget_token: null,
    metadata: { orderId: "ORD-001" },
    createdAt: "2026-02-27T10:00:00Z",
    transactionDate: "2026-02-27",
  },
  {
    id: "pi_002",
    amount: 150000,
    currency: "CLP",
    status: "succeeded",
    recipientAccount: {
      holderId: "76.123.456-7",
      holderName: "Mi Empresa SpA",
      institutionId: "bch",
      number: "00-987-65432-10",
      type: "checking_account",
    },
    senderAccount: {
      holderId: "98.765.432-1",
      holderName: "María González",
      institutionId: "bsa",
      number: "00-111-22233-44",
      type: "checking_account",
    },
    widget_token: null,
    metadata: { orderId: "ORD-002", plan: "premium" },
    createdAt: "2026-02-26T15:30:00Z",
    transactionDate: "2026-02-26",
  },
  {
    id: "pi_003",
    amount: 45000,
    currency: "CLP",
    status: "failed",
    recipientAccount: {
      holderId: "76.123.456-7",
      holderName: "Mi Empresa SpA",
      institutionId: "bch",
      number: "00-987-65432-10",
      type: "checking_account",
    },
    senderAccount: null,
    widget_token: null,
    metadata: { orderId: "ORD-003" },
    createdAt: "2026-02-25T09:00:00Z",
    transactionDate: null,
  },
  {
    id: "pi_004",
    amount: 89900,
    currency: "CLP",
    status: "requires_payment",
    recipientAccount: {
      holderId: "76.123.456-7",
      holderName: "Mi Empresa SpA",
      institutionId: "bch",
      number: "00-987-65432-10",
      type: "checking_account",
    },
    senderAccount: null,
    widget_token: "pi_wt_abc123",
    metadata: { orderId: "ORD-004" },
    createdAt: "2026-02-27T14:00:00Z",
    transactionDate: null,
  },
  {
    id: "pi_005",
    amount: 500000,
    currency: "MXN",
    status: "succeeded",
    recipientAccount: {
      holderId: "XAXX010101000",
      holderName: "Mi Empresa MX SA de CV",
      institutionId: "bbva_mx",
      number: "012345678901234567",
      type: "clabe",
    },
    senderAccount: {
      holderId: null,
      holderName: "Carlos Rodríguez",
      institutionId: "banamex",
      number: "002345678901234567",
      type: "clabe",
    },
    widget_token: null,
    metadata: { orderId: "ORD-MX-001" },
    createdAt: "2026-02-26T18:00:00Z",
    transactionDate: "2026-02-26",
  },
];

// ── Checkout Sessions ──

export const mockCheckoutSessions: CheckoutSession[] = [
  {
    id: "cs_001",
    amount: 25000,
    currency: "CLP",
    status: "completed",
    paymentIntentId: "pi_001",
    successUrl: "https://mi-app.com/success",
    cancelUrl: "https://mi-app.com/cancel",
    url: "https://pay.fintoc.com/cs_001",
    customerEmail: "juan.perez@email.com",
    expiresAt: "2026-02-27T11:00:00Z",
    createdAt: "2026-02-27T10:00:00Z",
    metadata: { orderId: "ORD-001" },
  },
  {
    id: "cs_002",
    amount: 150000,
    currency: "CLP",
    status: "completed",
    paymentIntentId: "pi_002",
    successUrl: "https://mi-app.com/success",
    cancelUrl: "https://mi-app.com/cancel",
    url: "https://pay.fintoc.com/cs_002",
    customerEmail: "maria.gonzalez@email.com",
    expiresAt: "2026-02-26T16:30:00Z",
    createdAt: "2026-02-26T15:30:00Z",
    metadata: { orderId: "ORD-002" },
  },
  {
    id: "cs_003",
    amount: 89900,
    currency: "CLP",
    status: "open",
    paymentIntentId: "pi_004",
    successUrl: "https://mi-app.com/success",
    cancelUrl: "https://mi-app.com/cancel",
    url: "https://pay.fintoc.com/cs_003",
    customerEmail: null,
    expiresAt: "2026-02-27T15:00:00Z",
    createdAt: "2026-02-27T14:00:00Z",
    metadata: { orderId: "ORD-004" },
  },
  {
    id: "cs_004",
    amount: 30000,
    currency: "CLP",
    status: "expired",
    paymentIntentId: null,
    successUrl: "https://mi-app.com/success",
    cancelUrl: "https://mi-app.com/cancel",
    url: "https://pay.fintoc.com/cs_004",
    customerEmail: "test@email.com",
    expiresAt: "2026-02-20T12:00:00Z",
    createdAt: "2026-02-20T11:00:00Z",
    metadata: {},
  },
];

// ── Payment Links ──

export const mockPaymentLinks: PaymentLink[] = [
  {
    id: "pl_001",
    name: "Suscripción mensual Premium",
    description: "Plan Premium - acceso completo a la plataforma",
    amount: 29990,
    currency: "CLP",
    status: "active",
    url: "https://pay.fintoc.com/pl_001",
    paymentCount: 45,
    totalCollected: 1349550,
    expiresAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    metadata: { plan: "premium" },
  },
  {
    id: "pl_002",
    name: "Donación evento benéfico",
    description: "Donación para evento de caridad 2026",
    amount: 10000,
    currency: "CLP",
    status: "active",
    url: "https://pay.fintoc.com/pl_002",
    paymentCount: 120,
    totalCollected: 1200000,
    expiresAt: "2026-03-31T23:59:59Z",
    createdAt: "2026-02-01T10:00:00Z",
    metadata: { event: "caridad_2026" },
  },
  {
    id: "pl_003",
    name: "Pago curso online",
    description: "Curso de programación avanzada",
    amount: 59990,
    currency: "CLP",
    status: "expired",
    url: "https://pay.fintoc.com/pl_003",
    paymentCount: 30,
    totalCollected: 1799700,
    expiresAt: "2026-02-15T23:59:59Z",
    createdAt: "2026-01-15T00:00:00Z",
    metadata: { course: "prog_avanzada" },
  },
  {
    id: "pl_004",
    name: "Cobro servicios consultoría",
    description: null,
    amount: 500000,
    currency: "MXN",
    status: "active",
    url: "https://pay.fintoc.com/pl_004",
    paymentCount: 5,
    totalCollected: 2500000,
    expiresAt: null,
    createdAt: "2026-02-10T14:00:00Z",
    metadata: {},
  },
];

// ── Refunds ──

export const mockRefunds: Refund[] = [
  {
    id: "ref_001",
    amount: 25000,
    currency: "CLP",
    status: "succeeded",
    paymentIntentId: "pi_001",
    reason: "Producto no entregado",
    createdAt: "2026-02-27T12:00:00Z",
    completedAt: "2026-02-27T12:05:00Z",
  },
  {
    id: "ref_002",
    amount: 150000,
    currency: "CLP",
    status: "pending",
    paymentIntentId: "pi_002",
    reason: "Cobro duplicado",
    createdAt: "2026-02-27T10:00:00Z",
    completedAt: null,
  },
  {
    id: "ref_003",
    amount: 45000,
    currency: "CLP",
    status: "failed",
    paymentIntentId: "pi_003",
    reason: "Solicitud del cliente",
    createdAt: "2026-02-26T08:00:00Z",
    completedAt: null,
  },
];

// ── Transfer Accounts ──

export const mockTransferAccounts: TransferAccount[] = [
  {
    id: "ta_001",
    holderName: "Mi Empresa SpA",
    holderId: "76.123.456-7",
    institutionId: "bch",
    institutionName: "Banco de Chile",
    accountType: "checking_account",
    accountNumber: "00-987-65432-10",
    currency: "CLP",
    description: "Cuenta corriente principal",
    createdAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "ta_002",
    holderName: "Mi Empresa MX SA de CV",
    holderId: "XAXX010101000",
    institutionId: "bbva_mx",
    institutionName: "BBVA México",
    accountType: "clabe",
    accountNumber: "012345678901234567",
    currency: "MXN",
    description: "Cuenta CLABE operaciones México",
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "ta_003",
    holderName: "Mi Empresa SpA",
    holderId: "76.123.456-7",
    institutionId: "bse",
    institutionName: "BancoEstado",
    accountType: "sight_account",
    accountNumber: "00-555-12345-67",
    currency: "CLP",
    description: "Cuenta vista nómina",
    createdAt: "2025-11-01T00:00:00Z",
  },
];

// ── Subscription Intents ──

export const mockSubscriptionIntents: SubscriptionIntent[] = [
  {
    id: "si_001",
    status: "succeeded",
    widgetToken: "si_wt_abc123",
    customerName: "Pedro Soto",
    customerEmail: "pedro.soto@email.com",
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "si_002",
    status: "succeeded",
    widgetToken: "si_wt_def456",
    customerName: "Laura Muñoz",
    customerEmail: "laura.munoz@email.com",
    createdAt: "2026-02-22T14:00:00Z",
  },
  {
    id: "si_003",
    status: "created",
    widgetToken: "si_wt_ghi789",
    customerName: null,
    customerEmail: null,
    createdAt: "2026-02-27T09:00:00Z",
  },
];

// ── Subscriptions ──

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub_001",
    status: "active",
    customerName: "Pedro Soto",
    customerEmail: "pedro.soto@email.com",
    mandateId: "mnd_001",
    institutionId: "bch",
    institutionName: "Banco de Chile",
    accountNumber: "****5678",
    totalCharges: 3,
    lastChargeDate: "2026-02-25",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sub_002",
    status: "active",
    customerName: "Laura Muñoz",
    customerEmail: "laura.munoz@email.com",
    mandateId: "mnd_002",
    institutionId: "bsa",
    institutionName: "Banco Santander",
    accountNumber: "****9012",
    totalCharges: 1,
    lastChargeDate: "2026-02-22",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "sub_003",
    status: "cancelled",
    customerName: "Diego Ramírez",
    customerEmail: "diego.ramirez@email.com",
    mandateId: "mnd_003",
    institutionId: "bbi",
    institutionName: "Banco BCI",
    accountNumber: "****3456",
    totalCharges: 6,
    lastChargeDate: "2026-02-10",
    createdAt: "2025-09-01T00:00:00Z",
  },
];

// ── Charges ──

export const mockCharges: Charge[] = [
  {
    id: "chg_001",
    subscriptionId: "sub_001",
    amount: 29990,
    currency: "CLP",
    status: "succeeded",
    description: "Cobro mensual enero",
    createdAt: "2026-01-01T08:00:00Z",
    paidAt: "2026-01-01T08:05:00Z",
  },
  {
    id: "chg_002",
    subscriptionId: "sub_001",
    amount: 29990,
    currency: "CLP",
    status: "succeeded",
    description: "Cobro mensual febrero",
    createdAt: "2026-02-01T08:00:00Z",
    paidAt: "2026-02-01T08:03:00Z",
  },
  {
    id: "chg_003",
    subscriptionId: "sub_001",
    amount: 29990,
    currency: "CLP",
    status: "succeeded",
    description: "Cobro mensual febrero (extra)",
    createdAt: "2026-02-25T08:00:00Z",
    paidAt: "2026-02-25T08:02:00Z",
  },
  {
    id: "chg_004",
    subscriptionId: "sub_002",
    amount: 15000,
    currency: "CLP",
    status: "succeeded",
    description: "Cobro mensual febrero",
    createdAt: "2026-02-22T08:00:00Z",
    paidAt: "2026-02-22T08:04:00Z",
  },
  {
    id: "chg_005",
    subscriptionId: "sub_003",
    amount: 29990,
    currency: "CLP",
    status: "failed",
    description: "Cobro mensual febrero",
    createdAt: "2026-02-10T08:00:00Z",
    paidAt: null,
  },
];

// ── Banking Links ──

export const mockBankingLinks: BankingLink[] = [
  {
    id: "link_001",
    holderName: "Pedro Soto",
    holderId: "18.123.456-7",
    holderType: "individual",
    institutionId: "bch",
    institutionName: "Banco de Chile",
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    lastRefreshedAt: "2026-02-27T06:00:00Z",
    accounts: [
      {
        id: "la_001",
        name: "Cuenta Corriente",
        officialName: "Cuenta Corriente Personas",
        number: "****5678",
        type: "checking_account",
        currency: "CLP",
        balance: { available: 1250000, current: 1350000 },
      },
      {
        id: "la_002",
        name: "Cuenta Vista",
        officialName: "Cuenta RUT",
        number: "****1234",
        type: "sight_account",
        currency: "CLP",
        balance: { available: 85000, current: 85000 },
      },
    ],
  },
  {
    id: "link_002",
    holderName: "Laura Muñoz",
    holderId: "19.876.543-2",
    holderType: "individual",
    institutionId: "bsa",
    institutionName: "Banco Santander",
    status: "active",
    createdAt: "2026-02-05T14:00:00Z",
    lastRefreshedAt: "2026-02-27T05:30:00Z",
    accounts: [
      {
        id: "la_003",
        name: "Cuenta Corriente",
        officialName: "Cuenta Corriente Santander",
        number: "****9012",
        type: "checking_account",
        currency: "CLP",
        balance: { available: 3450000, current: 3500000 },
      },
    ],
  },
  {
    id: "link_003",
    holderName: "Importadora ABC Ltda",
    holderId: "76.999.888-K",
    holderType: "business",
    institutionId: "bbi",
    institutionName: "Banco BCI",
    status: "inactive",
    createdAt: "2025-11-20T09:00:00Z",
    lastRefreshedAt: "2026-01-15T06:00:00Z",
    accounts: [
      {
        id: "la_004",
        name: "Cuenta Corriente Empresa",
        officialName: "Cuenta Corriente Empresas BCI",
        number: "****3456",
        type: "checking_account",
        currency: "CLP",
        balance: { available: 15670000, current: 16000000 },
      },
    ],
  },
];

// ── Movements ──

export const mockMovements: Movement[] = [
  {
    id: "mov_001",
    amount: 500000,
    currency: "CLP",
    description: "Transferencia recibida - Juan Pérez",
    postDate: "2026-02-27",
    transactionDate: "2026-02-27",
    type: "credit",
    accountId: "la_001",
    recipientAccount: null,
    senderAccount: {
      holderName: "Juan Pérez",
      holderId: "12.345.678-9",
      institutionName: "BancoEstado",
      number: "****7890",
    },
    comment: "Pago arriendo",
    referenceId: null,
  },
  {
    id: "mov_002",
    amount: 125000,
    currency: "CLP",
    description: "Compra en comercio - Supermercado Líder",
    postDate: "2026-02-27",
    transactionDate: "2026-02-27",
    type: "debit",
    accountId: "la_001",
    recipientAccount: {
      holderName: "Walmart Chile",
      holderId: null,
      institutionName: null,
      number: null,
    },
    senderAccount: null,
    comment: null,
    referenceId: "REF-LIDER-001",
  },
  {
    id: "mov_003",
    amount: 89990,
    currency: "CLP",
    description: "Pago automático - Netflix",
    postDate: "2026-02-26",
    transactionDate: "2026-02-26",
    type: "debit",
    accountId: "la_001",
    recipientAccount: {
      holderName: "Netflix International",
      holderId: null,
      institutionName: null,
      number: null,
    },
    senderAccount: null,
    comment: "Suscripción mensual",
    referenceId: null,
  },
  {
    id: "mov_004",
    amount: 2500000,
    currency: "CLP",
    description: "Depósito - Nómina empresa",
    postDate: "2026-02-25",
    transactionDate: "2026-02-25",
    type: "credit",
    accountId: "la_001",
    recipientAccount: null,
    senderAccount: {
      holderName: "Mi Empresa SpA",
      holderId: "76.123.456-7",
      institutionName: "Banco de Chile",
      number: "****6543",
    },
    comment: "Sueldo febrero 2026",
    referenceId: null,
  },
  {
    id: "mov_005",
    amount: 35000,
    currency: "CLP",
    description: "Transferencia enviada - María González",
    postDate: "2026-02-25",
    transactionDate: "2026-02-25",
    type: "debit",
    accountId: "la_001",
    recipientAccount: {
      holderName: "María González",
      holderId: "98.765.432-1",
      institutionName: "BancoEstado",
      number: "****4567",
    },
    senderAccount: null,
    comment: "Almuerzo compartido",
    referenceId: null,
  },
  {
    id: "mov_006",
    amount: 1500000,
    currency: "CLP",
    description: "Transferencia recibida - Startup Chile",
    postDate: "2026-02-24",
    transactionDate: "2026-02-24",
    type: "credit",
    accountId: "la_003",
    recipientAccount: null,
    senderAccount: {
      holderName: "Startup Chile SPA",
      holderId: "77.888.999-0",
      institutionName: "Banco Itaú",
      number: "****6677",
    },
    comment: "Reembolso viaje",
    referenceId: null,
  },
  {
    id: "mov_007",
    amount: 250000,
    currency: "CLP",
    description: "Pago tarjeta crédito",
    postDate: "2026-02-23",
    transactionDate: "2026-02-23",
    type: "debit",
    accountId: "la_003",
    recipientAccount: {
      holderName: "Banco Santander - TC",
      holderId: null,
      institutionName: "Banco Santander",
      number: null,
    },
    senderAccount: null,
    comment: "Pago parcial TC",
    referenceId: null,
  },
];

// ── Refresh Intents ──

export const mockRefreshIntents: RefreshIntent[] = [
  {
    id: "ri_001",
    linkId: "link_001",
    type: "only_last",
    status: "completed",
    createdAt: "2026-02-27T06:00:00Z",
    completedAt: "2026-02-27T06:02:00Z",
  },
  {
    id: "ri_002",
    linkId: "link_002",
    type: "only_last",
    status: "completed",
    createdAt: "2026-02-27T05:30:00Z",
    completedAt: "2026-02-27T05:32:00Z",
  },
];

// ── Team Members ──

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm_001",
    name: "Alejandro Silva",
    email: "alejandro.silva@miempresa.com",
    role: "administrator",
    status: "active",
    invitedAt: "2025-01-01T00:00:00Z",
    joinedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tm_002",
    name: "Camila Reyes",
    email: "camila.reyes@miempresa.com",
    role: "operations",
    status: "active",
    invitedAt: "2025-03-15T10:00:00Z",
    joinedAt: "2025-03-15T12:00:00Z",
  },
  {
    id: "tm_003",
    name: "Felipe Herrera",
    email: "felipe.herrera@miempresa.com",
    role: "developer",
    status: "active",
    invitedAt: "2025-06-01T09:00:00Z",
    joinedAt: "2025-06-02T08:00:00Z",
  },
  {
    id: "tm_004",
    name: "Valentina Torres",
    email: "valentina.torres@miempresa.com",
    role: "viewer",
    status: "invited",
    invitedAt: "2026-02-25T14:00:00Z",
    joinedAt: null,
  },
  {
    id: "tm_005",
    name: "Rodrigo Vargas",
    email: "rodrigo.vargas@miempresa.com",
    role: "operations",
    status: "disabled",
    invitedAt: "2025-02-01T00:00:00Z",
    joinedAt: "2025-02-01T10:00:00Z",
  },
];

// ── API Keys ──

export const mockApiKeys: ApiKeyInfo[] = [
  {
    type: "public",
    environment: "test",
    prefix: "pk_test_****",
    createdAt: "2025-01-01T00:00:00Z",
    lastUsedAt: "2026-02-27T10:00:00Z",
    ipRestrictions: { enabled: false, allowedIps: [] },
  },
  {
    type: "secret",
    environment: "test",
    prefix: "sk_test_****",
    createdAt: "2025-01-01T00:00:00Z",
    lastUsedAt: "2026-02-27T11:00:00Z",
    ipRestrictions: { enabled: false, allowedIps: [] },
  },
  {
    type: "public",
    environment: "live",
    prefix: "pk_live_****",
    createdAt: "2025-01-01T00:00:00Z",
    lastUsedAt: "2026-02-27T09:00:00Z",
    ipRestrictions: { enabled: true, allowedIps: ["203.0.113.0/24", "198.51.100.42"] },
  },
  {
    type: "secret",
    environment: "live",
    prefix: "sk_live_****",
    createdAt: "2025-01-01T00:00:00Z",
    lastUsedAt: "2026-02-27T12:00:00Z",
    ipRestrictions: { enabled: true, allowedIps: ["203.0.113.0/24", "198.51.100.42"] },
  },
];

// ── Reports ──

export const mockReports: Report[] = [
  {
    id: "rpt_001",
    type: "payout_reconciliation",
    status: "ready",
    dateRange: { from: "2026-02-01", to: "2026-02-15" },
    createdAt: "2026-02-16T06:00:00Z",
    downloadUrl: "https://api.fintoc.com/reports/rpt_001/download",
    format: "csv",
  },
  {
    id: "rpt_002",
    type: "daily_transactions",
    status: "ready",
    dateRange: { from: "2026-02-26", to: "2026-02-26" },
    createdAt: "2026-02-27T06:00:00Z",
    downloadUrl: "https://api.fintoc.com/reports/rpt_002/download",
    format: "csv",
  },
  {
    id: "rpt_003",
    type: "transfers_summary",
    status: "ready",
    dateRange: { from: "2026-02-01", to: "2026-02-27" },
    createdAt: "2026-02-27T07:00:00Z",
    downloadUrl: "https://api.fintoc.com/reports/rpt_003/download",
    format: "xlsx",
  },
  {
    id: "rpt_004",
    type: "payout_reconciliation",
    status: "pending",
    dateRange: { from: "2026-02-16", to: "2026-02-28" },
    createdAt: "2026-02-27T12:00:00Z",
    downloadUrl: null,
    format: "csv",
  },
];

// ── Institutions ──

export const mockInstitutions: Institution[] = [
  {
    id: "bch",
    name: "Banco de Chile",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bse",
    name: "BancoEstado",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bsa",
    name: "Banco Santander",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bbi",
    name: "Banco BCI",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bit",
    name: "Banco Itaú",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bfa",
    name: "Banco Falabella",
    country: "CL",
    supportedProducts: ["payments", "movements"],
    holderTypes: ["individual"],
    status: "active",
  },
  {
    id: "bsc",
    name: "Banco Scotiabank",
    country: "CL",
    supportedProducts: ["payments", "transfers", "movements"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "bri",
    name: "Banco Ripley",
    country: "CL",
    supportedProducts: ["payments"],
    holderTypes: ["individual"],
    status: "active",
  },
  {
    id: "bbva_mx",
    name: "BBVA México",
    country: "MX",
    supportedProducts: ["payments", "transfers"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "banamex",
    name: "Citibanamex",
    country: "MX",
    supportedProducts: ["payments", "transfers"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "banorte",
    name: "Banorte",
    country: "MX",
    supportedProducts: ["payments", "transfers"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "hsbc_mx",
    name: "HSBC México",
    country: "MX",
    supportedProducts: ["payments"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
  {
    id: "santander_mx",
    name: "Santander México",
    country: "MX",
    supportedProducts: ["payments", "transfers"],
    holderTypes: ["individual", "business"],
    status: "active",
  },
];
